export const poultryProducts = [
  // --- Batch 1 (Products 1–8) ---
  { name: "ZES-40", image: "/poultry-products/ZES_40.webp" },
  { name: "SELEMIX PLUS", image: "/poultry-products/SELEMIX_PLUS.webp" },
  { name: "LIVOCID SUPER", image: "/poultry-products/LIVOCID_SUPER.webp" },
  { name: "ORACID", image: "/poultry-products/ORACID.webp" },
  { name: "ASTAR VIT-C", image: "/poultry-products/ASTAR_VIT_C.webp" },

  // --- Batch 2 (Products 9–16) ---
  { name: "C-VIT 60", image: "/poultry-products/C_VIT_60.webp" },
  { name: "C-BOSTAR", image: "/poultry-products/C_BOSTAR.webp" },
  { name: "BROMO FRESH", image: "/poultry-products/BROMO_FRESH.webp" },
  { name: "ADEKON", image: "/poultry-products/ADEKON.webp" },
  { name: "ELECTROSAAL", image: "/poultry-products/ELECTROSAAL.webp" },
  { name: "BROMOBIN", image: "/poultry-products/BROMOBIN.webp" },
  { name: "ASTARLYTE", image: "/poultry-products/astarlyte.webp" },
  {
    name: "ASTOLINO MYCO FIX",
    image: "/poultry-products/astolino myco fix.webp",
  },
  { name: "ASTRA LIS", image: "/poultry-products/astra-lis.webp" },
  { name: "ASTRAL LIVO", image: "/poultry-products/astral livo.webp" },
  { name: "ASTRAL AMP", image: "/poultry-products/astral-amp.webp" },
  { name: "ASTRAL ESEL10", image: "/poultry-products/astral-esel10.webp" },
  { name: "ASTRAL L55", image: "/poultry-products/astral-l55.webp" },
  { name: "ASTRAL R80", image: "/poultry-products/astral-r80.webp" },
  { name: "BENTOMI", image: "/poultry-products/bentomi.webp" },
  { name: "BIO PH", image: "/poultry-products/bio ph.webp" },
  { name: "C VIT 60", image: "/poultry-products/c vit 60.webp" },
  { name: "CELA 54", image: "/poultry-products/cela-54.webp" },
  { name: "CYNARACHOL", image: "/poultry-products/cynarachol.webp" },
  { name: "IMMUNE FORCE", image: "/poultry-products/immune-force.webp" },
  { name: "LISO EC", image: "/poultry-products/liso-ec.webp" },
  { name: "MICROVIT 1000", image: "/poultry-products/microvit-1000.webp" },
  { name: "URI NUX", image: "/poultry-products/uri nux.webp" },
];

export const livestockProducts = [
  // --- Standard 8 Products ---
  { name: "Astar Phos", image: "/livestock-products/Astar_Phos.webp" },
  { name: "FEED PICKER", image: "/livestock-products/FEED_PICKER.webp" },
  {
    name: "Temp Tone Liquid",
    image: "/livestock-products/Temp_Tone_Liquid.webp",
  },
  { name: "COLCUS", image: "/livestock-products/COLCUS.webp" },
  { name: "Minrall", image: "/livestock-products/minrall.webp" },
  { name: "POULT UP", image: "/livestock-products/POULT_UP.webp" },
  { name: "Astar Jest", image: "/livestock-products/Astar_Jest.webp" },
  { name: "DEE PHOSPHATE", image: "/livestock-products/DEE_PHOSPHATE.webp" },

  // --- Group A Products ---
  { name: "SABROFIT-DS", image: "/livestock-products/SABROFIT-DS.webp" },
  { name: "MEG NILL", image: "/livestock-products/MEG_NILL.webp" },
  { name: "REPFIT", image: "/livestock-products/REPFIT.webp" },
  { name: "HI-H", image: "/livestock-products/HI-H_Oral_Liquid.webp" },
  { name: "Jatimix", image: "/livestock-products/Jatimix_Oral_Liquid.webp" },
  { name: "KOFLET", image: "/livestock-products/KOFLET_Cough_Syrup.webp" },
  { name: "CALCIFUR 200", image: "/livestock-products/CALCIFUR_200.webp" },
  { name: "AP-D DCP", image: "/livestock-products/AP-D_DCP.webp" },
  {
    name: "ASTRAD Bird Cure",
    image: "/livestock-products/ASTRAD_Bird_Cure.webp",
  },
  { name: "ASTRALIT-C", image: "/livestock-products/ASTRALIT-C.webp" },
  {
    name: "ASTOLINO MYCO FIX",
    image: "/livestock-products/ASTOLINO_MYCO_FIX.webp",
  },
  {
    name: "Aster Yeast Powder",
    image: "/livestock-products/Aster_Yeast_Powder.webp",
  },
  { name: "EYEON", image: "/livestock-products/EYEON_Eye_Solution.webp" },
  {
    name: "AP DC55 Happy DOG",
    image: "/livestock-products/AP_DC55_Happy_DOG.webp",
  },
  { name: "C-BOSTAR", image: "/livestock-products/C-BOSTAR.webp" },
  { name: "Astral M22", image: "/livestock-products/Astral_M22.webp" },
  { name: "Prolastre", image: "/livestock-products/Prolastre_SOLUTION.webp" },
  {
    name: "ASTRAL CAL",
    image: "/livestock-products/ASTRAL_CAL_MILK_BOOSTER_LIQUID.webp",
  },
  {
    name: "ASTRAL METHA",
    image: "/livestock-products/ASTRAL_METHA_ORAL_SOLUTION.webp",
  },

  // --- Group B Products ---
  { name: "Phospho-D", image: "/livestock-products/PHOSPHO-D.webp" },
  { name: "Sabrosal DF", image: "/livestock-products/SABROSAL_DF.webp" },
  { name: "AP M100", image: "/livestock-products/AP_M100.webp" },
  { name: "Emerc-21", image: "/livestock-products/EMERC-21.webp" },
  { name: "Astar-Deak", image: "/livestock-products/ASTAR-DEAK.webp" },
  { name: "Astar C", image: "/livestock-products/Astar_C.webp" },
  { name: "Udder-H", image: "/livestock-products/UDDER-H.webp" },
  { name: "AP Toxitony", image: "/livestock-products/AP_TOXITONY.webp" },
  { name: "Tempsal Liquid", image: "/livestock-products/TEMPSAL_Liquid.webp" },
  { name: "AP D-Col", image: "/livestock-products/AP_D-COL.webp" },
  { name: "Astral Livo", image: "/livestock-products/ASTRAL_LIVO.webp" },
  { name: "Astral N10", image: "/livestock-products/ASTRAL_N10.webp" },
  { name: "Astral Kuf10", image: "/livestock-products/ASTRAL_KUF10.webp" },
  { name: "Orgasal", image: "/livestock-products/ORGASAL.webp" },
  {
    name: "Astral Dicalcium Phosphate 100",
    image: "/livestock-products/ASTRAL_DICALCIUM_PHOSPHATE_100.webp",
  },
  {
    name: "Astral Pulsatilla",
    image: "/livestock-products/ASTRAL_PULSATILLA.webp",
  },
  { name: "AP Magsol50", image: "/livestock-products/AP_MAGSOL50.webp" },
  {
    name: "Astral Nila Stone Braker",
    image: "/livestock-products/ASTRAL_NILA_STONE_BRAKER.webp",
  },
  { name: "AP Call-D", image: "/livestock-products/AP_CALL-D.webp" },
  {
    name: "Astrot Yeastamin",
    image: "/livestock-products/ASTROT_YEASTAMIN.webp",
  },
  { name: "Elvix 50", image: "/livestock-products/ELVIX_50.webp" },
  { name: "Astral Esel-10", image: "/livestock-products/ASTRAL_ESEL_10.webp" },
  { name: "Bentomi", image: "/livestock-products/BENTOMI.webp" },
  { name: "Astra Lis", image: "/livestock-products/ASTRA_LIS.webp" },
  { name: "Astral Carb", image: "/livestock-products/ASTRAL_CARB.webp" },
  { name: "Astar Sept", image: "/livestock-products/ASTAR_SEPT.webp" },
];
